### ISSUE TITLE
file missing on ankiweb

### ISSUE THREAD

**Issue by ijgnd** [Arthur-Milchior/anki-link-to-open-browser#1]
the version on ankiweb from 2020-03-31 does not contain a file "link.svg" which I think is the reason for this error message I get when I try to open an Add window:

    Debug info:
    Anki 2.1.24 (d3964603) Python 3.8.1 Qt 5.14.1 PyQt 5.14.1
    Platform: Linux
    Flags: frz=True ao=True sv=1
    Add-ons, last update check: 2020-04-07 11:28:31
    Add-ons possibly involved: ⁨Links between notes cards to open browser and previewer⁩

    Caught exception:
    Traceback (most recent call last):
    File "aqt/webview.py", line 31, in cmd
    File "aqt/webview.py", line 97, in _onCmd
    File "aqt/webview.py", line 500, in _onBridgeCmd
    File "aqt/toolbar.py", line 154, in _linkHandler
    File "aqt/toolbar.py", line 169, in _addLinkHandler
    File "aqt/main.py", line 989, in onAddCard
    File "aqt/__init__.py", line 94, in open
    File "aqt/addcards.py", line 40, in __init__
    File "aqt/addcards.py", line 52, in setupEditor
    File "aqt/editor.py", line 92, in __init__
    File "aqt/editor.py", line 173, in setupWeb
    File "anki/hooks.py", line 596, in runFilter
    File ".../Anki2/addons21/1126950429/editor.py", line 94, in setupEditorButtonsFilter
        editor.addButton(
    File "aqt/editor.py", line 230, in addButton
    File "aqt/editor.py", line 255, in _addButton
    File "aqt/editor.py", line 204, in resourceToData
    FileNotFoundError

**Comment by Arthur-Milchior** [comment]
Please update and let me know if it works. Thanks

**Comment by ijgnd** [comment]
Thanks for the quick reply. It's still not right for me. Now the error has disappeared but I only have these files in the addon folder "11269504292" and no function:

    $ ls 1126950429
    __init__.py  LICENSE  meta.json  README.md  zipping

and zipping contains

    rm ????.zip
    zip -R ????.zip config.* *.ui *.sh *.py *.css *.js web  LICENSE *.md zipping --exclude \*~ \*zip ankiweb

**Comment by Arthur-Milchior** [comment]
My bad, I did put the wrong zip. Corrected

**Comment by ijgnd** [comment]
it works. Thanks.

**Comment by Arthur-Milchior** [comment]
Thanks to you for dealing with my mistakes in a constructive way
