### ISSUE TITLE
i stops working

### ISSUE THREAD

**Issue by dumbdreamed** [Arthur-Milchior/anki-link-to-open-browser#2]
hi, my friend thanks for your beautiful addon.
unfortunately, it stops working after once I clicked the link that I created. and after that, it gives neither the error nor the desired functionality. I disabled all of the other add ons but the issue remains.
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.25 (898801eb) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-04-30 03:26:36

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 34, in cmd
  File "aqt\webview.py", line 114, in _onCmd
  File "aqt\webview.py", line 512, in _onBridgeCmd
  File "aqt\gui_hooks.py", line 2091, in __call__
  File "C:\Users\dumbdreamed\AppData\Roaming\Anki2\addons21\1126950429\previewer.py", line 11, in on_bridge_browser
    cids = mw.col.find_cards(search)
  File "lib\site-packages\anki\collection.py", line 614, in find_cards
  File "lib\site-packages\anki\rsbackend.py", line 490, in search_cards
  File "lib\site-packages\anki\rsbackend.py", line 257, in _run_command
anki.rsbackend.StringError: InvalidInput { info: "unable to parse search" }

**Comment by Arthur-Milchior** [comment]
It seems it did open the browser and failed to do a search.  If it is the case, can you please let me know what is in the browser search bar ?
Otherwise, can you open the note in the editor, select the field, press ctrl+shift+x and copy here the content of the window that was opened. So that I can see the actual content of the field.
Other solution would be to export the card with the broken link and send it to me.
